# Dockerfile.train
FROM public.ecr.aws/sagemaker/pytorch-training:2.1.0-cpu-py310-ubuntu20.04

WORKDIR /opt/program

# dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# app code
COPY . .

# SageMaker training entrypoint
ENTRYPOINT ["python", "-u", "train_entrypoint.py"]